### ISSUE TITLE
About ipv6 address listen

### ISSUE THREAD

**Issue by wlynxg** [vikulin/gomobile#3]
After my test, I found that the public IPv6 address starting with 240e can be listened to normally on Android, but the LAN IPv6 address such as fe80 cannot be listened to normally.
I tried to look at the Android source code to see the cause of this problem.

Let's discuss this issue later. Can you delete the discussion at https://github.com/golang/go/pull/61089#issuecomment-2178820464? Because the ipv6 problem is not the same as the problem discussed there, to avoid causing trouble to those who come to check later

**Comment by wlynxg** [comment]
@vikulin  I have found the problem, I will sort it out and post it later.

**Comment by wlynxg** [comment]
For detailed reasons, please see https://github.com/golang/go/issues/68082. I have fixed this problem in anet. You can use anet to solve this problem.

**Comment by vikulin** [comment]
@wlynxg thank you a lot for so rapid reply and result. I will try new version of Anet lib in an hour.

**Comment by vikulin** [comment]
Fixed.
